name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 0 0 ? * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 5
          commit_message: "Updated readme with the latest blog post"
          feed_list: "https://blog.nativecloud.dev/rss/"