name: Latest Podcast Episodes
on:
  schedule:
    # Runs every hour
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-podcast:
    name: Update this repo's README with latest Podcast Episodes from Anchor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 5
          commit_message: "Updated readme with the latest episode"
          comment_tag_name: "PODCAST"
          feed_list: "https://anchor.fm/s/unwyred/podcast/rss"